# Generated by Django 3.2.5 on 2021-08-13 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sauna', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='person',
            new_name='person_id',
        ),
    ]
