# Generated by Django 3.2.5 on 2021-08-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sauna', '0002_rename_person_visit_person_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privilege', models.BooleanField()),
                ('number', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
