# Generated by Django 3.2.5 on 2022-03-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sauna', '0006_tarif'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarif',
            new_name='Tariff',
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['privilege', 'number'], 'verbose_name': 'Прайс', 'verbose_name_plural': 'Прайсы'},
        ),
        migrations.AlterField(
            model_name='price',
            name='privilege',
            field=models.BooleanField(verbose_name='Льготный'),
        ),
    ]
