# Generated by Django 3.2.5 on 2022-03-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sauna', '0007_auto_20220311_1048'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tariff',
            new_name='Payment',
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date'], 'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['privilege', 'number'], 'verbose_name': 'Цена', 'verbose_name_plural': 'Цены'},
        ),
        migrations.AlterField(
            model_name='price',
            name='privilege',
            field=models.BooleanField(verbose_name='Льгота'),
        ),
    ]
